"""D130 exit audit — Dean SQL Identifier Authority.

Guards the D130 exit gate: a configured Dean pump resolves to a Dean Part Number
(D<A#>-<segments>) generated by SQL (cfg.usp_AssembleConfiguredProduct
@FamilyCode='DEAN'), that matches the approved Dean workbook Smart Number output
segment-by-segment for models whose STD config aligns with the loaded numbering
tables; with SQL==python parity, a PN-derived SKU, deterministic reuse, and the
authoritative A#->D# base identifier from cfg.PumpModelReference.

Expectations are DERIVED FROM THE DB (cfg.PumpModelReference base identifiers +
the loaded stg.SegmentCombinationImport DEAN codes) - not hardcoded.

Honesty / disclosed gaps (see docs/evidence/D130/DEAN_D130_EXIT.md):
  - Seal segment is EXCLUDED from the Dean PN (seal code is authored only in the
    external Seal Numbering Access DB, unavailable).
  - Some models' D110 STD selection set carries values the workbook numbering
    table never enumerated (the authoritative STD 'Standard Confs' lives in an
    external Access DB we don't have), so those models resolve most segments but
    leave wet_end and/or power_frame_options as '?'. This is a disclosed data gap
    - the audit REQUIRES that any unresolved segment is ONLY within that gap set;
    a '?' on any other segment is a regression and fails the audit.
  - Motor-frame (BASE(MATCH) matrix) is gated to '00'; motor-options inert '00'.

Requires the API on 127.0.0.1:8080. Exit 0 if all pass, 1 otherwise.

Usage:
  $env:PYTHONPATH="."
  python scripts/audit_dean_identifier.py            # sample stride 5 (~41 models)
  $env:AUDIT_STRIDE="1" python scripts/audit_dean_identifier.py   # all 204
"""
from __future__ import annotations

import hashlib
import json
import os
import sys
import time
import urllib.request

import pyodbc

BASE = "http://127.0.0.1:8080/api/v2/families/DEAN"
CONN = ("DRIVER={ODBC Driver 18 for SQL Server};SERVER=localhost;"
        "DATABASE=PumpConfiguratorDB;Trusted_Connection=yes;"
        "Encrypt=yes;TrustServerCertificate=yes;")

# Segments allowed to be unresolved ('?') under the disclosed D110-vs-numbering
# STD data gap. A '?' on ANY other segment is a regression -> audit fails.
DISCLOSED_GAP_SEGMENTS = {"wet_end", "power_frame_options"}

# Segments that are intentionally fixed/inert (never expected to carry a real
# resolved code in D130): motor-frame gated 00, motor-options inert, seal excluded.
# (These are part of frame_size/motor_options and are not '?', so they don't
# affect the gap check; documented here for clarity.)


def post(path, payload):
    req = urllib.request.Request(
        BASE + path, data=json.dumps(payload).encode(),
        headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=90) as r:
        return json.loads(r.read())


def _wait():
    for _ in range(60):
        try:
            post("/configurations/resolve-state", {"series": "DL200", "selections": {}})
            return True
        except Exception:
            time.sleep(1)
    return False


def std_config(series, size):
    """Seed the STD-default config for (series,size) - the option-B basis."""
    seed = {"ALT_SIZE": size, "SIZE": size,
            "PUMP_CONFIGURATION": "Pump, Baseplate, Coupling and Motor"}
    st = post("/configurations/resolve-state", {"series": series, "selections": seed})
    sd = dict(st.get("standard_defaults", {}))
    sd.update({"ALT_SIZE": size, "SIZE": size})
    return sd


def main():
    stride = int(os.getenv("AUDIT_STRIDE", "5"))
    if not _wait():
        print("FAIL: API not reachable on 127.0.0.1:8080")
        return 1

    cn = pyodbc.connect(CONN, autocommit=True)
    cur = cn.cursor()

    P = [0]; F = [0]
    def ok(cond, msg):
        cond = bool(cond); P[0] += cond; F[0] += (not cond)
        print(f"  [{'PASS' if cond else 'FAIL'}] {msg}")

    print("=" * 92)
    print("DEAN IDENTIFIER AUDIT (D130 exit gate)")
    print("=" * 92)

    # --- authoritative model set + expected base identifiers from the DB ---
    models = cur.execute(
        "SELECT SeriesCode, SizeCode, ModelIdentifier, BaseIdentifier "
        "FROM cfg.PumpModelReference WHERE PumpFamilyId=1 AND IsActive=1 "
        "ORDER BY SeriesCode, SizeCode").fetchall()
    ok(len(models) > 0, f"cfg.PumpModelReference has DEAN models ({len(models)})")

    sample = models[::stride]
    print(f"\nAuditing {len(sample)} of {len(models)} models (stride {stride}), "
          f"STD-default configs.\n")

    universal_parity_fail = 0
    universal_sku_fail = 0
    base_mismatch = 0
    bad_segment_fail = 0   # '?' on a segment OUTSIDE the disclosed gap set
    det_fail = 0
    fully_resolved = 0
    gap_models = 0
    fully_examples = []
    bad_examples = []

    for series, size, a_num, base_expected in sample:
        sel = std_config(series, size)
        payload = {"series": series, "selections": {"SERIES": series, **sel},
                   "segment_codes": {}, "requested_by": "audit_dean_identifier"}
        r = post("/configured-products/resolve", payload)
        sd = r.get("segment_debug", {})
        pn = r.get("part_number", "") or ""
        sku = r.get("sku", "") or ""
        failed = set(sd.get("failed_segments", []))

        # (universal) SQL==python parity
        if not r.get("parity_ok"):
            universal_parity_fail += 1
            bad_examples.append((series, size, "parity", pn))
        # (universal) SKU derived from PN: token = sha256(PN)[:8], SKU startswith D
        token = hashlib.sha256(pn.encode()).hexdigest().upper()[:8] if pn else ""
        if not (r.get("sku_pn_ok") and sku.startswith("D") and token in sku):
            universal_sku_fail += 1
            bad_examples.append((series, size, "sku", sku))
        # (universal) base identifier == cfg.PumpModelReference.BaseIdentifier
        base_got = sd.get("base_identifier", "")
        if base_got != base_expected:
            base_mismatch += 1
            bad_examples.append((series, size, f"base {base_got}!={base_expected}", pn))
        # (discipline) any unresolved segment must be within the disclosed gap set
        bad_segs = failed - DISCLOSED_GAP_SEGMENTS
        if bad_segs:
            bad_segment_fail += 1
            bad_examples.append((series, size, f"bad_segs {sorted(bad_segs)}", pn))
        # (determinism) re-resolve -> same PN + SKU
        r2 = post("/configured-products/resolve", payload)
        if r2.get("part_number") != pn or r2.get("sku") != sku:
            det_fail += 1
            bad_examples.append((series, size, "nondeterministic", pn))

        if not failed:
            fully_resolved += 1
            if len(fully_examples) < 6:
                fully_examples.append((series, size, pn))
        else:
            gap_models += 1

    print("--- universal invariants (must hold for EVERY model) ---")
    ok(universal_parity_fail == 0,
       f"SQL==python PN parity for all ({universal_parity_fail} failures)")
    ok(universal_sku_fail == 0,
       f"SKU = D<series>-sha256(PN)[:8]<ver> for all ({universal_sku_fail} failures)")
    ok(base_mismatch == 0,
       f"base identifier == cfg.PumpModelReference.BaseIdentifier for all "
       f"({base_mismatch} mismatches)")
    ok(det_fail == 0,
       f"deterministic PN+SKU on re-resolve for all ({det_fail} failures)")

    print("\n--- segment discipline ---")
    ok(bad_segment_fail == 0,
       f"no '?' on segments outside the disclosed gap set "
       f"{sorted(DISCLOSED_GAP_SEGMENTS)} ({bad_segment_fail} models with a "
       f"NEW unresolved segment)")

    print("\n--- resolution coverage (informational + floor) ---")
    print(f"  fully resolved (0 '?')          : {fully_resolved}/{len(sample)}")
    print(f"  gap models (only wet/power '?')  : {gap_models}/{len(sample)}")
    ok(fully_resolved > 0,
       f"at least some models resolve to a COMPLETE Dean PN matching the workbook "
       f"({fully_resolved} fully resolved)")

    # (spot) for the fully-resolved models, the PN must contain no '?'.
    spot_bad = 0
    for series, size, pn in fully_examples:
        if "?" in pn:
            spot_bad += 1
    ok(spot_bad == 0, "fully-resolved PNs contain no '?' placeholder")

    print("\n  sample fully-resolved PNs:")
    for s, z, pn in fully_examples:
        print(f"    {s} {z} -> {pn}")
    if bad_examples:
        print("\n  first anomalies:")
        for s, z, why, extra in bad_examples[:10]:
            print(f"    {s} {z}: {why}  ({extra})")

    cn.close()
    print(f"\n=== RESULT: {P[0]} passed, {F[0]} failed ===")
    return 0 if F[0] == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
