USE master;
GO
IF DB_ID(N'PumpConfiguratorDB') IS NOT NULL
BEGIN
    ALTER DATABASE PumpConfiguratorDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE PumpConfiguratorDB;
END;
GO
CREATE DATABASE PumpConfiguratorDB;
GO
ALTER DATABASE PumpConfiguratorDB SET RECOVERY SIMPLE;
ALTER DATABASE PumpConfiguratorDB SET READ_COMMITTED_SNAPSHOT ON;
GO
USE PumpConfiguratorDB;
GO
CREATE SCHEMA cfg AUTHORIZATION dbo;
GO
CREATE SCHEMA price AUTHORIZATION dbo;
GO
CREATE SCHEMA quote AUTHORIZATION dbo;
GO
CREATE SCHEMA stg AUTHORIZATION dbo;
GO
CREATE SCHEMA audit AUTHORIZATION dbo;
GO
